site_name: Philterd Policy Editor
repo_url: https://github.com/philterd/philterd-policy-editor
site_url: https://philterd.github.io/philterd-policy-editor//
edit_uri: '?query=docs/docs/'
copyright: Copyright 2026 Philterd, LLC
site_author: philterd
site_description: User guide for the Philterd Policy Editor, which generates redaction policies for Philter and Phileas.
theme:
  name: material
  locale: en
  palette:
    primary: red
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage Guide: usage.md
  - FAQ: faq.md
